# -*- coding: utf-8 -*-
"""DEG_Filtering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yRIJFxJRSbsXWJE2WyuWEc_nscSeqo2J
"""

import pandas as pd
import numpy as np
ptc = ['GSE3467','GSE3678','GSE5364',
            'GSE33630','GSE53157','GSE58545','GSE60542','GSE171011','GSE9115','GSE29265','GSE27155']
ftc = ['GSE27155','GSE53157']
atc = ['GSE33630','GSE29265','GSE53072','GSE65144','GSE9115','GSE27155']

#replace "-" with directory for all instances
def process(filename,file):
  df = pd.read_csv(filename,sep="\t")
  print("Gene count for ",file,":",len(df))
  data = df[(df['logFC']<-0.5) | (df['logFC']>0.5)]
  data = data[(data['P.Value']<=0.05)]
  print("DEGs: ",file,":",len(data))
  data.to_csv("-/"+file+".csv")

for d in atc:
  file = "-/"+d+".top.table.tsv"
  process(file,d)

#filtering up and down regulated genes
for i in range(0,len(atc)):
  filename = "-/"+atc[i]+".csv"
  df = pd.read_csv(filename)
  up = df[(df['logFC']>0.5)]
  down = df[(df['logFC']<-0.5)]
  print("up genes: ",filename,":",len(up))
  print("down genes: ",filename,":",len(down))
  up.dropna(inplace=True)
  down.dropna(inplace=True)
  up.to_csv(ftc[i]+"-up.csv")
  down.to_csv(ftc[i]+"-down.csv")

genes = set()
data = ftc
df = pd.read_csv(data[0]+".csv")
genes = set(df['Gene.symbol'].str.strip())

for i in range(1,len(data)):
  df = pd.read_csv(data[i]+".csv")
  genes = genes.intersection(set(df['Gene.symbol']))

print(len(genes))
import csv
genelist = list(genes)
with open('intersection_genes.csv','w',newline='') as cs:
  cswriter = csv.writer(cs)
  cswriter.writerows(zip(genelist))

