# -*- coding: utf-8 -*-
"""go-freq.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVX_zzYPizrZVnQwR_To6TZ4leT0l6cx
"""

import pandas as pd
import numpy as np
#replace - with gene file
gene_file = '-'
genes = pd.read_csv(gene_file,header=None)
genes.columns = ['gene']
genes['BP'] = 0
genes['CC'] = 0
genes['MF'] = 0

#replace - with output file name
go = pd.read_csv('-.csv')
go.head()

for index,row in go.iterrows():
  gns = [g.strip() for g in row["Genes"].split(',')]
  for g in gns:
    term = row['Category']
    genes.loc[genes['gene']==g,term] += 1

genes

#replace - with input file name for kegg data
kegg = pd.read_csv('-.csv')
kegg.head()

genes['KEGG'] = 0
genes

for index,row in kegg.iterrows():
  gns = [g.strip() for g in row["Genes"].split(',')]
  for g in gns:
    genes.loc[genes['gene']==g,'KEGG'] += 1

genes

#replace - with output file name
genes.to_csv('-.csv')