# -*- coding: utf-8 -*-
"""expressed_genes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kl5K1TER12mQOOJ3MJY9knRmwyl6fkDS
"""

import pandas as pd
ptc = ['GSE3467','GSE3678','GSE5364',
            'GSE33630','GSE53157','GSE58545','GSE60542','GSE171011','GSE9115','GSE29265','GSE27155']
atc = ['GSE33630','GSE29265','GSE53072','GSE65144','GSE9115','GSE27155']
ftc = ['GSE27155','GSE53157']

#script to find the hub genes that are up and down regulated in each datasets of each THCA
#replace - with filepath
rel_path = "-"
hub_up = pd.read_csv(rel_path,header=None)
hub_up.columns = ['genes']
hub_down = pd.read_csv(rel_path,header=None)
hub_down.columns = ['genes']

for i in atc:
    data = pd.read_csv(rel_path + i + "-up.csv")
    data_genes = set(data['Gene.symbol'].astype(str).str.upper())  # Convert to uppercase for case-insensitive matching

    for gene in hub_up['genes']:
        if gene.upper() in data_genes:
            print("Gene", gene, "present in", i)
            hub_up.loc[hub_up['genes'] == gene, i] = "Y"
hub_up.fillna('-',inplace=True)
hub_up.to_csv(rel_path+"up_data.csv")

import pandas as pd

for i in atc:
    data = pd.read_csv(rel_path + i + "-down.csv")
    data_genes = set(data['Gene.symbol'].astype(str).str.upper())  # Convert to uppercase for case-insensitive matching

    for gene in hub_down['genes']:
        if gene.upper() in data_genes:
            print("Gene", gene, "present in", i)
            hub_down.loc[hub_down['genes'] == gene, i] = "Y"
hub_down.fillna('-',inplace=True)
hub_down.to_csv(rel_path+"down_data.csv")

