# -*- coding: utf-8 -*-
"""hubgenes_ranking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Gh48RYM_voxM8zt9Y3NLj03yB9hmZPz
"""

#find he frequency of hub genes in different topological orders
import pandas as pd
#replace - with input file name
genes = pd.read_csv('-.csv',header=None)
genes.columns = ['genes']
genes['<5'] = 0
genes['>=5'] = 0
genes

orders = ['Betweenness','BottleNeck','Closeness','ClusteringCoefficient',
          'DMNC','Degree','EPC','EcCentricity','MCC','MNC','Radiality','Stress']
for o in orders:
  file = +o+".csv"
  data = pd.read_csv(file,header=None,skiprows=2)
  data.columns = ['Rank','Name','Score']
  for ind,row in data.iterrows():
    gene = row['Name']
    rank = int(row['Rank'])
    if rank <5:
      genes.loc[genes['genes']==gene,'<5'] += 1
    else:
      genes.loc[genes['genes']==gene,'>=5'] += 1
genes

#replace - with output file name
genes.to_csv("-.csv")

